## Samples
samples: "SAMPLE1 SAMPLE2 SAMPLE3 
          SAMPLE4 SAMPLE5 SAMPLE6
          SAMPLE7 SAMPLE8 SAMPLE9"

lane: "_L005_R1_001"

## Step names
step1: qC # quality control
step2: map # map to reference
step3: counts # counts

## Info
# adapters
adapters: /home/dataset/adapters.fa

## Directories
# Base data dir
base_dir: /home/dataset/

# Change to location of all raw .sam files
raw_data_dir: /home/dataset/rawData/

# Path to reference genome
ref_genome: /home/dataset/Mus_musculus.GRCm39.dna.toplevel.fa 

# Path to gtf file
gtf_file: /home/dataset/Mus_musculus.GRCm39.104.gtf  

# Genome index dir
genomeindexdir: /home/dataset/starIndex/

# Rsem prepare ref dir
rsemprepref: /home/dataset/rsemRef
